# This workflow will do a clean install of node dependencies, build the source code and publish to branch gh-pages

name: CI gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./dev

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - run: npm ci
      working-directory: ${{env.working-directory}}

    - run: npm run build
      working-directory: ${{env.working-directory}}

    - run: npm test
      env:
        CI: true
      working-directory: ${{env.working-directory}}

    - name: Publish github pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/StorkST/CoreRussianVerbs.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ${{env.working-directory}}
